import React from 'react';
import EditableText from '@ui/EditableText';

export interface IStatsItem {
  key: string
  number: string
  text: string
  detail: string
}

export interface IStatsProps {
  title: string
  description: string
  stats: IStatsItem[]
}

const Stats_10: React.FC<IStatsProps> = ({
  title = "Transforming Workspaces Globally",
  description = "At our design studio, we reimagine workplaces to be more dynamic, collaborative, and conducive to creativity.",
  stats = [
    {
      key: "users",
      number: "250k",
      text: "Creative Minds Engaged",
      detail: "Joining a community of forward-thinking professionals."
    },
    {
      key: "revenue",
      number: "$8.9 billion",
      text: "Revenue Generated by Our Clients",
      detail: "Empowering businesses to achieve their highest potential."
    },
    {
      key: "transactions",
      number: "401,093",
      text: "Successful Projects Delivered",
      detail: "Crafting spaces that inspire innovation and productivity."
    }
  ]
}) =>{
  return (
    <div className="bg-white dark:bg-slate-800 py-16 sm:py-20">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-2xl lg:mx-0">
          <h2 className="TITLE-PRIMARY text-3xl font-bold tracking-tight text-slate-900 dark:text-slate-50 sm:text-4xl">
            <EditableText propKey={`title`}>{title}</EditableText>
          </h2>
          <p className="DESC mt-6 text-base leading-7 text-slate-700 dark:text-slate-300">
            <EditableText propKey={`description`}>{description}</EditableText>
          </p>
        </div>
        <div className="mx-auto mt-16 flex max-w-2xl flex-col gap-8 lg:mx-0 lg:mt-20 lg:max-w-none lg:flex-row lg:items-end">
          {stats.map((stat, index) => (
            <div key={stat.key} className={`flex flex-col-reverse justify-between gap-x-16 gap-y-8 rounded-2xl ${index === 1 ? 'bg-gray-900 dark:bg-slate-900' : 'bg-gray-50 dark:bg-slate-800 dark:border border-black/10 dark:border-white/10'} p-8 sm:w-${index === 2 ? '11/12' : '3/4'} sm:max-w-md sm:flex-row-reverse sm:items-end lg:w-full lg:max-w-none lg:flex-auto lg:flex-col lg:items-start ${index === 1 ? 'lg:gap-y-44' : 'lg:gap-y-28'}`}>
              <p className={`TEXT-CONTENT flex-none text-3xl font-bold tracking-tight ${index === 1 ? 'text-white' : 'text-slate-900 dark:text-white'}`}>
                <EditableText propKey={`stats_${index}_number`}>{stat.number}</EditableText>
              </p>
              <div className="sm:w-80 sm:shrink lg:w-auto lg:flex-none">
                <p className={`TITLE-SECONDARY text-lg font-semibold tracking-tight ${index === 1 ? 'text-white' : 'text-slate-900 dark:text-white'}`}>
                  <EditableText propKey={`stats_${index}_text`}>{stat.text}</EditableText>
                </p>
                <p className={`DESC mt-2 text-base leading-7 ${index === 1 ? 'text-white/70' : 'text-slate-600 dark:text-slate-300'}`}>
                  <EditableText propKey={`stats_${index}_detail`}>{stat.detail}</EditableText>
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default Stats_10;